# Generated by Django 4.2.1 on 2023-06-06 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='headline',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='profile_image/placeholder.jpg', upload_to='profile_image/%Y-%m-%d'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
