# Generated by Django 4.2.1 on 2023-06-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
