# Generated by Django 4.2.1 on 2023-06-06 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
