# Generated by Django 4.2.1 on 2023-06-13 09:06

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_additionalfile'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='course',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='thumbnail',
            field=models.ImageField(default='profile_image/placeholder.jpg', upload_to='category_thumbnail/%Y-%m-%d'),
        ),
    ]
