# Generated by Django 4.2.1 on 2023-06-26 06:45

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_delete_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalfile',
            name='file',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='additional_files/%Y-%m-%d'),
        ),
    ]
