# Generated by Django 4.2.1 on 2023-06-27 20:32

import cloudinary_storage.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_lecture_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='video',
            field=models.FileField(storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='lecture_video/%Y-%m-%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'flv', 'mov', 'ogv', '3gp', '3g2', 'wmv', 'mpeg', 'flv', 'mkv', 'avi'])]),
        ),
    ]
