# Generated by Django 4.2.1 on 2023-06-27 21:22

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_alter_lecture_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
